//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace specflowPoC.Locators {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CreateUserLocators {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateUserLocators() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("specflowPoC.Locators.CreateUserLocators", typeof(CreateUserLocators).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to brokerId.
        /// </summary>
        internal static string ID_brokerageOrganizationDropdown {
            get {
                return ResourceManager.GetString("ID_brokerageOrganizationDropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carrierId.
        /// </summary>
        internal static string ID_carrierOrganizationDropdown {
            get {
                return ResourceManager.GetString("ID_carrierOrganizationDropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to csioNetId.
        /// </summary>
        internal static string ID_csioNetIdInputField {
            get {
                return ResourceManager.GetString("ID_csioNetIdInputField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email.
        /// </summary>
        internal static string ID_emailInputField {
            get {
                return ResourceManager.GetString("ID_emailInputField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        internal static string ID_nameInputField {
            get {
                return ResourceManager.GetString("ID_nameInputField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to organizationUserId.
        /// </summary>
        internal static string ID_organizationUserIdInputField {
            get {
                return ResourceManager.GetString("ID_organizationUserIdInputField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to userId.
        /// </summary>
        internal static string ID_userIdInputField {
            get {
                return ResourceManager.GetString("ID_userIdInputField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tr[descendant::td[.=&apos;{0}&apos;]]//div[contains(@class,&apos;container&apos;)].
        /// </summary>
        internal static string XPATH_accessToModulesCheckbox {
            get {
                return ResourceManager.GetString("XPATH_accessToModulesCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //button[text()=&apos;Cancel&apos;].
        /// </summary>
        internal static string XPATH_cancelButton {
            get {
                return ResourceManager.GetString("XPATH_cancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@type=&apos;file&apos;].
        /// </summary>
        internal static string XPATH_chooseFileButton {
            get {
                return ResourceManager.GetString("XPATH_chooseFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //mat-option.
        /// </summary>
        internal static string XPATH_dropdownOptions {
            get {
                return ResourceManager.GetString("XPATH_dropdownOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;box&apos;][descendant::h2[text()=&apos;Organization&apos;]]//div[@class=&apos;mat-radio-outer-circle&apos;].
        /// </summary>
        internal static string XPATH_organizationTypeRadioButton {
            get {
                return ResourceManager.GetString("XPATH_organizationTypeRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //button[text()=&apos;Save&apos;].
        /// </summary>
        internal static string XPATH_saveButton {
            get {
                return ResourceManager.GetString("XPATH_saveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;box&apos;][descendant::h2[text()=&apos;New User&apos;]]//div[@class=&apos;mat-radio-outer-circle&apos;].
        /// </summary>
        internal static string XPATH_userTyperadioButton {
            get {
                return ResourceManager.GetString("XPATH_userTyperadioButton", resourceCulture);
            }
        }
    }
}
