//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace specflowPoC.Locators {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CreateSingleESlipLocators {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateSingleESlipLocators() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("specflowPoC.Locators.CreateSingleESlipLocators", typeof(CreateSingleESlipLocators).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entryText.
        /// </summary>
        internal static string ID_backTextEntryInputField {
            get {
                return ResourceManager.GetString("ID_backTextEntryInputField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entryTitle.
        /// </summary>
        internal static string ID_backTextTitleInputField {
            get {
                return ResourceManager.GetString("ID_backTextTitleInputField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to address1.
        /// </summary>
        internal static string ID_contactAddress1InputField {
            get {
                return ResourceManager.GetString("ID_contactAddress1InputField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to address2.
        /// </summary>
        internal static string ID_contactAddress2InputField {
            get {
                return ResourceManager.GetString("ID_contactAddress2InputField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to city.
        /// </summary>
        internal static string ID_contactCityInputField {
            get {
                return ResourceManager.GetString("ID_contactCityInputField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to postalCode.
        /// </summary>
        internal static string ID_contactPostalCodeInputField {
            get {
                return ResourceManager.GetString("ID_contactPostalCodeInputField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to effectiveDate.
        /// </summary>
        internal static string ID_effectiveDateInputField {
            get {
                return ResourceManager.GetString("ID_effectiveDateInputField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email.
        /// </summary>
        internal static string ID_emailInputField {
            get {
                return ResourceManager.GetString("ID_emailInputField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expirationDate.
        /// </summary>
        internal static string ID_expirationDateInputField {
            get {
                return ResourceManager.GetString("ID_expirationDateInputField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insurerAddress.
        /// </summary>
        internal static string ID_insurerAddressInputField {
            get {
                return ResourceManager.GetString("ID_insurerAddressInputField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insurer.
        /// </summary>
        internal static string ID_insurerDropdown {
            get {
                return ResourceManager.GetString("ID_insurerDropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to preferedLang.
        /// </summary>
        internal static string ID_languageDropdown {
            get {
                return ResourceManager.GetString("ID_languageDropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customerName.
        /// </summary>
        internal static string ID_nameInputField {
            get {
                return ResourceManager.GetString("ID_nameInputField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phoneNumber.
        /// </summary>
        internal static string ID_phoneNumberInputField {
            get {
                return ResourceManager.GetString("ID_phoneNumberInputField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to policyNumber.
        /// </summary>
        internal static string ID_policyNumberInputField {
            get {
                return ResourceManager.GetString("ID_policyNumberInputField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to provinceId.
        /// </summary>
        internal static string ID_provinceDropdown {
            get {
                return ResourceManager.GetString("ID_provinceDropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message.
        /// </summary>
        internal static string ID_sendPreviewMessageInputField {
            get {
                return ResourceManager.GetString("ID_sendPreviewMessageInputField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to salutation.
        /// </summary>
        internal static string ID_sendPreviewSalutationInputField {
            get {
                return ResourceManager.GetString("ID_sendPreviewSalutationInputField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vehicleMake.
        /// </summary>
        internal static string ID_vehicleMakeInputField {
            get {
                return ResourceManager.GetString("ID_vehicleMakeInputField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vehicleModel.
        /// </summary>
        internal static string ID_vehicleModelInputField {
            get {
                return ResourceManager.GetString("ID_vehicleModelInputField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vehicleYear.
        /// </summary>
        internal static string ID_vehicleYearInputField {
            get {
                return ResourceManager.GetString("ID_vehicleYearInputField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vinNumber.
        /// </summary>
        internal static string ID_vinNumberInputField {
            get {
                return ResourceManager.GetString("ID_vinNumberInputField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //button[text()=&apos;Add Entry&apos;].
        /// </summary>
        internal static string XPATH_addBackTextButton {
            get {
                return ResourceManager.GetString("XPATH_addBackTextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //button[text()=&apos;Add Vehicle&apos;].
        /// </summary>
        internal static string XPATH_addVehicleButton {
            get {
                return ResourceManager.GetString("XPATH_addVehicleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //ngui-auto-complete//li[contains(text(),&apos;{0}&apos;)].
        /// </summary>
        internal static string XPATH_autocompletePopup {
            get {
                return ResourceManager.GetString("XPATH_autocompletePopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //button[text()=&apos;Back&apos;].
        /// </summary>
        internal static string XPATH_backButton {
            get {
                return ResourceManager.GetString("XPATH_backButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tr[descendant::td[2][text()=&apos;{0}&apos;]]//td[1].
        /// </summary>
        internal static string XPATH_backTextPositionOnTheList {
            get {
                return ResourceManager.GetString("XPATH_backTextPositionOnTheList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //eslip-back-text//table//tr.
        /// </summary>
        internal static string XPATH_backTextsList {
            get {
                return ResourceManager.GetString("XPATH_backTextsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tr[descendant::td[2][text()=&apos;{0}&apos;]].
        /// </summary>
        internal static string XPATH_backTextWithTitleExistance {
            get {
                return ResourceManager.GetString("XPATH_backTextWithTitleExistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;brokerage-field&apos;]//input.
        /// </summary>
        internal static string XPATH_brokerageInputField {
            get {
                return ResourceManager.GetString("XPATH_brokerageInputField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;carrier-field&apos;]//input.
        /// </summary>
        internal static string XPATH_carrierInputField {
            get {
                return ResourceManager.GetString("XPATH_carrierInputField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //button[text()=&apos;Clear&apos;].
        /// </summary>
        internal static string XPATH_clearBackTextEntryButton {
            get {
                return ResourceManager.GetString("XPATH_clearBackTextEntryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //mat-option.
        /// </summary>
        internal static string XPATH_dropdownOptions {
            get {
                return ResourceManager.GetString("XPATH_dropdownOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tr[descendant::td[2][text()=&apos;{0}&apos;]]//button//*[contains(@class,&apos;edit&apos;)].
        /// </summary>
        internal static string XPATH_editBackTextByTitleButton {
            get {
                return ResourceManager.GetString("XPATH_editBackTextByTitleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //td/*[@name=&apos;entryText&apos;].
        /// </summary>
        internal static string XPATH_editBackTextEntryInputField {
            get {
                return ResourceManager.GetString("XPATH_editBackTextEntryInputField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //td/*[@name=&apos;entryTitle&apos;].
        /// </summary>
        internal static string XPATH_editBackTextTitleInputField {
            get {
                return ResourceManager.GetString("XPATH_editBackTextTitleInputField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tr[descendant::td[2][text()=&apos;{0}&apos;]]//button//*[contains(@class,&apos;edit&apos;)].
        /// </summary>
        internal static string XPATH_editVehicleByVinButton {
            get {
                return ResourceManager.GetString("XPATH_editVehicleByVinButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //td/*[@name=&apos;make&apos;].
        /// </summary>
        internal static string XPATH_editVehicleMakeInputField {
            get {
                return ResourceManager.GetString("XPATH_editVehicleMakeInputField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //td/*[@name=&apos;model&apos;].
        /// </summary>
        internal static string XPATH_editVehicleModelInputField {
            get {
                return ResourceManager.GetString("XPATH_editVehicleModelInputField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //td/*[@name=&apos;year&apos;].
        /// </summary>
        internal static string XPATH_editVehicleYearInputField {
            get {
                return ResourceManager.GetString("XPATH_editVehicleYearInputField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //td/*[@name=&apos;vinNumber&apos;].
        /// </summary>
        internal static string XPATH_editVinNumberInputField {
            get {
                return ResourceManager.GetString("XPATH_editVinNumberInputField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tr[descendant::td[2][text()=&apos;{0}&apos;]]//button//*[contains(@class,&apos;down&apos;)].
        /// </summary>
        internal static string XPATH_moveDownBackTextByTitleButton {
            get {
                return ResourceManager.GetString("XPATH_moveDownBackTextByTitleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tr[descendant::td[2][text()=&apos;{0}&apos;]]//button//*[contains(@class,&apos;down&apos;)].
        /// </summary>
        internal static string XPATH_moveDownVehicleByVinButton {
            get {
                return ResourceManager.GetString("XPATH_moveDownVehicleByVinButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tr[descendant::td[2][text()=&apos;{0}&apos;]]//button//*[contains(@class,&apos;up&apos;)].
        /// </summary>
        internal static string XPATH_moveUpBackTextByTitleButton {
            get {
                return ResourceManager.GetString("XPATH_moveUpBackTextByTitleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tr[descendant::td[2][text()=&apos;{0}&apos;]]//button//*[contains(@class,&apos;up&apos;)].
        /// </summary>
        internal static string XPATH_moveUpVehicleByVinButton {
            get {
                return ResourceManager.GetString("XPATH_moveUpVehicleByVinButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //button[text()=&apos;Next&apos;].
        /// </summary>
        internal static string XPATH_nextButton {
            get {
                return ResourceManager.GetString("XPATH_nextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //main//h1.
        /// </summary>
        internal static string XPATH_pageTitle {
            get {
                return ResourceManager.GetString("XPATH_pageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tr[descendant::td[2][text()=&apos;{0}&apos;]]//button//*[contains(@class,&apos;delete&apos;)].
        /// </summary>
        internal static string XPATH_removeBackTextByTitleButton {
            get {
                return ResourceManager.GetString("XPATH_removeBackTextByTitleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tr[descendant::td[2][text()=&apos;{0}&apos;]]//button//*[contains(@class,&apos;delete&apos;)].
        /// </summary>
        internal static string XPATH_removeVehicleByVinButton {
            get {
                return ResourceManager.GetString("XPATH_removeVehicleByVinButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //button[text()=&apos;Save&apos;].
        /// </summary>
        internal static string XPATH_saveButton {
            get {
                return ResourceManager.GetString("XPATH_saveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //button[@type=&apos;submit&apos;].
        /// </summary>
        internal static string XPATH_saveDraftButton {
            get {
                return ResourceManager.GetString("XPATH_saveDraftButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //button[text()=&apos;Send E-Slip&apos;].
        /// </summary>
        internal static string XPATH_sendESlipButton {
            get {
                return ResourceManager.GetString("XPATH_sendESlipButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //vehicle-information//table//tr.
        /// </summary>
        internal static string XPATH_vehicleList {
            get {
                return ResourceManager.GetString("XPATH_vehicleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tr[descendant::td[2][text()=&apos;{0}&apos;]]//td[1].
        /// </summary>
        internal static string XPATH_vehiclePositionOnTheList {
            get {
                return ResourceManager.GetString("XPATH_vehiclePositionOnTheList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tr[descendant::td[2][text()=&apos;{0}&apos;]].
        /// </summary>
        internal static string XPATH_vehicleWithVinExistance {
            get {
                return ResourceManager.GetString("XPATH_vehicleWithVinExistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //md-error/span.
        /// </summary>
        internal static string XPATH_warningMessages {
            get {
                return ResourceManager.GetString("XPATH_warningMessages", resourceCulture);
            }
        }
    }
}
