//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace specflowPoC.Locators {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ListOfDraftsLocators {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ListOfDraftsLocators() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("specflowPoC.Locators.ListOfDraftsLocators", typeof(ListOfDraftsLocators).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //button[text()=&apos;Delete&apos;].
        /// </summary>
        internal static string XPATH_deleteButton {
            get {
                return ResourceManager.GetString("XPATH_deleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //button[text()=&apos;Edit&apos;].
        /// </summary>
        internal static string XPATH_editButton {
            get {
                return ResourceManager.GetString("XPATH_editButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tr[descendant::td[contains(text(),&apos;{0}&apos;)]].
        /// </summary>
        internal static string XPATH_eSlipByName {
            get {
                return ResourceManager.GetString("XPATH_eSlipByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tr[descendant::td[contains(text(),&apos;{0}&apos;)]]//div[contains(@class,&apos;container&apos;)].
        /// </summary>
        internal static string XPATH_eSlipByNameCheckbox {
            get {
                return ResourceManager.GetString("XPATH_eSlipByNameCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tr[descendant::td[contains(text(),&apos;{0}&apos;)]]//td[9].
        /// </summary>
        internal static string XPATH_eSlipByNameState {
            get {
                return ResourceManager.GetString("XPATH_eSlipByNameState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[descendant::pagination-controls]//select.
        /// </summary>
        internal static string XPATH_paginationDropdown {
            get {
                return ResourceManager.GetString("XPATH_paginationDropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@class=&apos;pagination-next&apos;].
        /// </summary>
        internal static string XPATH_paginationNextButton {
            get {
                return ResourceManager.GetString("XPATH_paginationNextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@class=&apos;pagination-previous&apos;].
        /// </summary>
        internal static string XPATH_paginationPreviousButton {
            get {
                return ResourceManager.GetString("XPATH_paginationPreviousButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //button[text()=&apos;Send&apos;].
        /// </summary>
        internal static string XPATH_sendButton {
            get {
                return ResourceManager.GetString("XPATH_sendButton", resourceCulture);
            }
        }
    }
}
